# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actividad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RutaArchivo', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrupoAnimal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosApicolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductoApicolas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosUPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Propositos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proposito', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAve', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoUP', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUEA', models.CharField(max_length=255)),
                ('FechaCaracterizacion', models.DateField()),
                ('FechaActualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEmpleados', models.IntegerField()),
                ('Asociatividad', models.BooleanField(default=False)),
                ('AreaCultivada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AreaPastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NumeroPotreros', models.IntegerField()),
                ('NumeroInvernaderos', models.IntegerField()),
                ('NumeroTanques', models.IntegerField()),
                ('NumeroReservorios', models.IntegerField()),
                ('FuentesAgua', models.BooleanField(default=False)),
                ('FechaActualizacion', models.DateField()),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.actividadup')),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('GrupoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.grupoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionUPAgroindustrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('INVIMA', models.BooleanField(default=False)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.productosups')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionUPAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.productosups')),
            ],
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raza', models.CharField(max_length=255)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.animales')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePorcinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapeta', models.BooleanField(default=False)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEstanques', models.IntegerField()),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOvinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEquinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaprinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBovinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroMachos', models.IntegerField()),
                ('NumeroHembras', models.IntegerField()),
                ('RUV', models.CharField(max_length=255)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Proposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.propositos')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleApicolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('ProductosApicolas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.productosapicolas')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.animales')),
                ('Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.razas')),
                ('TipoAve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.tiposaves')),
            ],
        ),
        migrations.AddField(
            model_name='productosups',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.unidades'),
        ),
    ]
