# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Predios', '0001_initial'),
        ('UPs', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='up',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuarios.funcionarios'),
        ),
        migrations.AddField(
            model_name='up',
            name='Predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predios.predios'),
        ),
        migrations.AddField(
            model_name='up',
            name='Productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.productores'),
        ),
        migrations.AddField(
            model_name='up',
            name='TipoUP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.tipoup'),
        ),
        migrations.AddField(
            model_name='produccionupagroindustrial',
            name='UP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.up'),
        ),
        migrations.AddField(
            model_name='produccionupagricola',
            name='UP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.up'),
        ),
        migrations.AddField(
            model_name='detalleup',
            name='UP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.up'),
        ),
        migrations.AddField(
            model_name='archivosup',
            name='UP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.up'),
        ),
        migrations.AddField(
            model_name='animales',
            name='UP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPs.up'),
        ),
    ]
