# Generated by Django 6.0.1 on 2026-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up',
            name='RUEA',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
