# Generated by Django 6.0.1 on 2026-04-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_administradores_usuario_and_more'),
        ('Usuarios', '0003_empresas_nitempresa_alter_administradores_usuario_and_more'),
    ]

    operations = [
    ]
