# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('UPs', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calificacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotivosSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MotivoSolicitud', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoVisita', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSolicitud', models.DateField(auto_now_add=True)),
                ('Observacion', models.CharField(max_length=255)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Visitas.estados')),
                ('MotivoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Visitas.motivossolicitudes')),
                ('UP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UPs.up')),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVisita', models.DateField()),
                ('RutaDocumento', models.CharField(max_length=255)),
                ('Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_administrador', to='Usuarios.funcionarios')),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_funcionario', to='Usuarios.funcionarios')),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitas.solicitudes')),
                ('TipoVisita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Visitas.tiposvisitas')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('InventarioFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.inventariofuncionario')),
                ('Visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitas.visitas')),
            ],
        ),
        migrations.CreateModel(
            name='InfoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObservacionVisita', models.TextField()),
                ('AccionSeguimiento', models.CharField(max_length=255)),
                ('Firmado', models.BooleanField(default=False)),
                ('Calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Visitas.calificaciones')),
                ('Visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitas.visitas')),
            ],
        ),
    ]
