# Generated by Django 6.0.3 on 2026-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAsignacion', models.DateField()),
                ('FechaDevolucion', models.DateField(blank=True, null=True)),
                ('Entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardexInsumoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('FechaAsignacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Licencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=255)),
                ('Modelo', models.CharField(max_length=255)),
                ('FechaTecno', models.DateField()),
                ('FechaSoat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Herramienta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineasVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineaVehiculo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarcasVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarcaVehiculo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsignacionVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAsignacion', models.DateField()),
                ('FechaDevolucion', models.DateField(blank=True, null=True)),
                ('Entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCombustibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoCombustible', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoHerramienta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoVehiculo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnidadMedida', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
