# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramientas',
            name='Administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.administradores'),
        ),
        migrations.AddField(
            model_name='asignacionherramientas',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.funcionarios'),
        ),
        migrations.AddField(
            model_name='cardexinsumofuncionario',
            name='Administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.administradores'),
        ),
        migrations.AddField(
            model_name='cardexinsumofuncionario',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.funcionarios'),
        ),
        migrations.AddField(
            model_name='conductores',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.funcionarios'),
        ),
        migrations.AddField(
            model_name='asignacionherramientas',
            name='Herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.herramientas'),
        ),
        migrations.AddField(
            model_name='cardexinsumofuncionario',
            name='Insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.insumos'),
        ),
        migrations.AddField(
            model_name='inventariofuncionario',
            name='Funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.funcionarios'),
        ),
        migrations.AddField(
            model_name='inventariofuncionario',
            name='Insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.insumos'),
        ),
        migrations.AddField(
            model_name='lineasvehiculos',
            name='MarcaVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.marcasvehiculos'),
        ),
        migrations.AddField(
            model_name='registroasignacionvehiculos',
            name='Administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.administradores'),
        ),
        migrations.AddField(
            model_name='registroasignacionvehiculos',
            name='Conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.conductores'),
        ),
        migrations.AddField(
            model_name='registroasignacionvehiculos',
            name='DetalleVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.detallevehiculos'),
        ),
        migrations.AddField(
            model_name='herramientas',
            name='TipoHerramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.tiposherramientas'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='UnidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.unidadesmedida'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='LineaVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.lineasvehiculos'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='TipoCombustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.tiposcombustibles'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='TipoVehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.tiposvehiculos'),
        ),
        migrations.AddField(
            model_name='detallevehiculos',
            name='Vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.vehiculos'),
        ),
    ]
