# Generated by Django 6.0.3 on 2026-03-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_initial'),
        ('UPs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='UnidadMedida',
        ),
        migrations.AddField(
            model_name='insumos',
            name='Unidades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='UPs.unidades'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UnidadesMedida',
        ),
    ]
