# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSeguro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposRegistrosICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoICA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTenencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoTenencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePredio', models.CharField(max_length=255)),
                ('AreaPredio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('AccesoCredito', models.BooleanField(default=False)),
                ('UsoSuelo', models.BooleanField(default=False)),
                ('Latitud', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('Longitud', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Predios.sectores')),
                ('Seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Predios.seguros')),
                ('TiposRegistroICA', models.ManyToManyField(blank=True, to='Predios.tiposregistrosica')),
                ('TipoTenencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Predios.tipostenencias')),
            ],
        ),
        migrations.CreateModel(
            name='Veredas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreVereda', models.CharField(max_length=255)),
                ('Sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Predios.sectores')),
            ],
        ),
    ]
